layout:
  pages:
    - id: page_u4fv5vbm
      sections:
        - id: section_9456e995
          fields:
            - id: textField_7316b388
              display: textField
              state:
                visible: false
                read-only: false
              signpostPosition: right-middle
        - id: project_section
          fields:
            - id: project
              display: dropDown
              state:
                visible: true
                read-only: false
              signpostPosition: right-middle
        - id: deploymentName_section
          fields:
            - id: deploymentName
              display: textField
              state:
                visible: true
                read-only: false
              signpostPosition: right-middle
        - id: description_section
          fields:
            - id: description
              display: textArea
              state:
                visible: true
                read-only: false
              signpostPosition: right-middle
        - id: section_525em1e4
          fields:
            - id: Environment
              display: dropDown
              state:
                visible: true
                read-only:
                  - equals:
                      checkbox_640c9abb: true
                    value: true
                  - equals:
                      checkbox_640c9abb: false
                    value: false
              signpostPosition: right-middle
        - id: section_c4djee8q
          fields:
            - id: Region
              display: dropDown
              state:
                visible: true
                read-only:
                  - equals:
                      checkbox_640c9abb: true
                    value: true
                  - equals:
                      checkbox_640c9abb: false
                    value: false
              signpostPosition: right-middle
        - id: section_a04ba19e
          fields:
            - id: PodID
              display: dropDown
              state:
                visible: true
                read-only:
                  - equals:
                      checkbox_640c9abb: true
                    value: true
                  - equals:
                      checkbox_640c9abb: false
                    value: false
              signpostPosition: right-middle
        - id: section_ae4f60fc
          fields:
            - id: checkbox_640c9abb
              display: checkbox
              state:
                visible: true
                read-only: false
              signpostPosition: right-middle
        - id: section_axma9fw3
          fields:
            - id: inputJSON
              display: textField
              state:
                read-only: false
                visible:
                  - equals:
                      checkbox_640c9abb: true
                    value: true
                  - equals:
                      checkbox_640c9abb: false
                    value: false
              signpostPosition: right-middle
        - id: section_414a9972
          fields:
            - id: textField_4e12770e
              display: textField
              state:
                visible: false
                read-only: false
              signpostPosition: right-middle
      title: General
      state: {}
schema:
  textField_7316b388:
    label: ConfigName
    type:
      dataType: string
    default: WellsFargoPodAutomation
    placeholder: ''
    constraints: {}
  project:
    label: Project
    description: Project
    type:
      dataType: string
      isMultiple: false
    valueList:
      id: projects
      type: scriptAction
    constraints:
      required: true
  deploymentName:
    label: Deployment Name
    description: Deployment Name
    type:
      dataType: string
      isMultiple: false
    constraints:
      required: true
      max-value: 80
  description:
    label: Description
    description: Description
    type:
      dataType: string
      isMultiple: false
    constraints:
      max-value: 256
  Environment:
    label: Environment
    type:
      dataType: string
    valueList:
      id: com.vmware.pso.wellsfargo.json.ui/getPodEnvironment
      type: scriptAction
      parameters:
        - $type:
            dataType: string
          configName: textField_7316b388
        - $type:
            dataType: string
          configPath: textField_4e12770e
    constraints:
      required: false
  Region:
    label: Region
    type:
      dataType: string
    valueList:
      id: com.vmware.pso.wellsfargo.json.ui/getPodRegion
      type: scriptAction
      parameters:
        - $type:
            dataType: string
          configName: textField_7316b388
        - $type:
            dataType: string
          configPath: textField_4e12770e
        - $type:
            dataType: string
          environment: Environment
    constraints:
      required: false
  PodID:
    label: POD ID
    type:
      dataType: string
    valueList:
      id: com.vmware.pso.wellsfargo.json.ui/getPods
      type: scriptAction
      parameters:
        - $type:
            dataType: string
          region: Region
        - $type:
            dataType: string
          configName: textField_7316b388
        - $type:
            dataType: string
          configPath: textField_4e12770e
        - $type:
            dataType: string
          environment: Environment
    placeholder: ''
    constraints:
      required: false
  checkbox_640c9abb:
    label: Enable Override
    type:
      dataType: boolean
    constraints: {}
  inputJSON:
    label: Override JSON
    type:
      dataType: string
    constraints:
      required: false
  textField_4e12770e:
    label: ConfigPath
    type:
      dataType: string
    default: WellsFargo
    placeholder: ''
    constraints: {}
options:
  externalValidations: []
